version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/urujdas-deployment/
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 120
      runas: root